version: '3'
services:
  mysql:
    image: "mysql:latest"
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=zxcvasdf123
      - MYSQL_DATABASE=jjh
    volumes:
      - ./db/mysql/data:/var/lib/mysql
  app:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql
